# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  rules:
    # Style Rules
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    
    # Code Quality Rules  
    avoid_print: true
    avoid_empty_else: true
    avoid_returning_null_for_void: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true
    
    # Performance Rules
    prefer_for_elements_to_map_fromIterable: true
    prefer_spread_collections: true
    
    # Documentation Rules
    public_member_api_docs: false # Disable for now, enable later if needed
    
    # Import Rules
    directives_ordering: true
    sort_child_properties_last: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
